apiVersion: apps/v1
kind: deployment
metadata:
  name: chat-app-deployment
spec:
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app-container
        image: yunusemretosun/chatapp:2
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000