apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-app
  name: chat-app
  namespace: capp
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 32000