apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-app
  name: chat-app
  namespace: capp
spec:
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app-container
        image: yunusemretosun/chatapp:67
        envFrom:
            - configMapRef:
                name: django-config
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000